
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.swing.JOptionPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form House
     */
    public Booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        type = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        days = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox<>();
        comboxx = new javax.swing.JComboBox<>();
        confirm = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        numb = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tables = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        view = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        room = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        type.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        type.setText("Room Category");
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 116, 142, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rooms", "Deluxe", "Non-Deluxe", "Master" }));
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 120, 142, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Duration of Stay");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 160, -1, -1));

        days.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        days.setText("Stay Period");
        getContentPane().add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 204, 142, -1));

        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        getContentPane().add(combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 164, 142, -1));

        comboxx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Night", "Day" }));
        getContentPane().add(comboxx, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 208, 142, -1));

        confirm.setText("Confirm ");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 339, 83, -1));

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 339, 90, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Your Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 73, 142, -1));

        phone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phone.setText("Phone Number");
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 248, 142, -1));
        getContentPane().add(numb, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 252, 142, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 77, 142, -1));

        tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ROOM", "STATUS", "TYPE", "PRICE"
            }
        ));
        tables.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tables);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 73, -1, 133));

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tab);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 279, -1, 110));

        view.setText("View Your Details");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 419, -1, -1));

        jButton3.setText("Available");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 44, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("****Select the available room****");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 212, 240, -1));

        phone1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phone1.setText("Room");
        getContentPane().add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 286, 142, -1));
        getContentPane().add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 290, 142, -1));

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel7.setText("Book Your Room");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 6, 300, 61));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp5134857-pink-aesthetic-for-computer-wallpapers.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
    String Name = name.getText();
    String category = (String) combo.getSelectedItem();

    String stay = (String) combox.getSelectedItem();

    String period = (String) comboxx.getSelectedItem();

    String number = numb.getText();
    String Room = room.getText();
        try {
    // Load the MySQL JDBC driver
    Class.forName("com.mysql.cj.jdbc.Driver");

    // Database URL, change according to your setup
    String url = "jdbc:mysql://localhost:3306/hotel";

    // Connect to the database
    Connection connection = DriverManager.getConnection(url, "root", "");

    // Retrieve the data from the text fields
   

    // Prepare the SQL query
    String sql = "INSERT INTO booking (`Name`, `Category`, `stay`, `period`, `number`,`Room`) VALUES (?, ?, ?, ?, ?,?)";
    PreparedStatement statement = connection.prepareStatement(sql);
    statement.setString(1, Name);
    statement.setString(2, category);
    statement.setString(3, stay);
    statement.setString(4, period);
    statement.setString(5, number);
    statement.setString(6, Room);

    // Execute the query
    statement.executeUpdate();

    // Close the statement and connection
    statement.close();
    connection.close();

} catch(ClassNotFoundException | SQLException e){System.out.print(e);}     
        JOptionPane.showMessageDialog(null, "Thanks for Booking");
    
    }//GEN-LAST:event_confirmActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
     Management m = new Management();
     m.show();
     this.setVisible(false);
     
    }//GEN-LAST:event_cancelActionPerformed

    private void tablesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablesAncestorAdded
       updateTableData();
    }//GEN-LAST:event_tablesAncestorAdded

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
DefaultTableModel tb1Model = (DefaultTableModel)tab.getModel();
        tb1Model.setRowCount(0);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/hotel";
            Connection connection = DriverManager.getConnection(url, "root","");

            String sql = "SELECT * FROM booking";
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);

            while (rs.next()) {
                     String room  = rs.getString("Room");
                    String Room = rs.getString("Name");
                    String cat = rs.getString("Category");
                    
                    String number = rs.getString("number");
                    
               String tbData[] = {room,Room,cat,number}; 


               tb1Model.addRow(tbData);
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.print(e);}        // TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed

    private void updateTableData() {
       DefaultTableModel tb1Model = (DefaultTableModel) tables.getModel();
    tb1Model.setRowCount(0);

    try {
        // Load the JDBC driver
        Class.forName("com.mysql.cj.jdbc.Driver");
        // Establish a connection
        String url = "jdbc:mysql://localhost:3306/hotel";
        Connection connection = DriverManager.getConnection(url, "root", "");

        // Execute the query
        String sql = "SELECT Room, Status ,Type FROM managing";
        Statement statement = connection.createStatement();
        ResultSet rs = statement.executeQuery(sql);

        // Iterate through the result set and add rows to the table model
        while (rs.next()) {
            String Room = rs.getString("Room");
            String Status = rs.getString("Status");
            String Type = rs.getString("Type");

            // Add the data to the table model
            String[] rowData = {Room, Status,Type};
            tb1Model.addRow(rowData);
        }

        // Close the resources
        rs.close();
        statement.close();
        connection.close();
    } catch (ClassNotFoundException | SQLException e) {
        e.printStackTrace();
    
}
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JComboBox<String> comboxx;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel days;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField numb;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phone1;
    private javax.swing.JTextField room;
    private javax.swing.JTable tab;
    private javax.swing.JTable tables;
    private javax.swing.JLabel type;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
