
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class updeladd extends javax.swing.JFrame {

    /**
     * Creates new form updeladd
     */
    public updeladd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        del = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox<>();
        price = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tables = new javax.swing.JTable();
        view = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        room = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        type = new javax.swing.JLabel();
        comb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 365, -1, -1));

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 365, -1, -1));

        del.setText("DELETE");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 365, -1, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Occupied", "Under Maintenance" }));
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 131, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Status");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 67, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Price");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 67, 22));

        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spring", "Summer", "Winter" }));
        getContentPane().add(combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 131, -1));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 131, -1));

        tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room", "Status", "Season", "Price", "Type"
            }
        ));
        tables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tables);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 193));

        view.setText("VIEW");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Season");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 67, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Room");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 67, -1));

        room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomActionPerformed(evt);
            }
        });
        getContentPane().add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 131, -1));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 80, -1));

        type.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("Type");
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 37, -1));

        comb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DELUXE", "NON-DELUXE" }));
        comb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combActionPerformed(evt);
            }
        });
        getContentPane().add(comb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 131, -1));

        jLabel6.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel6.setText("Add Room");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 33, 208, 61));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp6262814-pink-aesthetic-1920x1080-wallpapers.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
    
        String Room = room.getText();
        String Status = (String) combo.getSelectedItem();
        String Season = (String) combox.getSelectedItem();
        String Price = price.getText();
        String Type = (String) comb.getSelectedItem();
       

         try{
            Class.forName("com.mysql.cj.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/hotel";


            Connection connection = DriverManager.getConnection(url, "root","");

            String sql = "INSERT INTO managing (Room, Status, Season, Price , Type) VALUES (?, ?, ?, ? ,?)";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, Room);
            statement.setString(2, Status);
            statement.setString(3, Season);
            statement.setString(4, Price);
            statement.setString(5, Type);
            statement.executeUpdate();

            JOptionPane.showMessageDialog(null,"Room Added");

         }catch(ClassNotFoundException | SQLException e){System.out.print(e);}
    }//GEN-LAST:event_addActionPerformed

    private void tablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesMouseClicked
        DefaultTableModel tb1Model = (DefaultTableModel)tables.getModel();

        //set data to text field when selceted
        String tb1RoomNo = tb1Model.getValueAt(tables.getSelectedRow(),0).toString();
        String tb1RoomType = tb1Model.getValueAt(tables.getSelectedRow(),1).toString();
        String tb1Status = tb1Model.getValueAt(tables.getSelectedRow(),2).toString();
        String tb1Rate = tb1Model.getValueAt(tables.getSelectedRow(),3).toString();
        String tb1type = tb1Model.getValueAt(tables.getSelectedRow(),4).toString();
        //set to textfield
        room.setText(tb1RoomNo);
        combo.setSelectedItem(tb1RoomType);
        combox.setSelectedItem(tb1Status);
        price.setText(tb1Rate);
        comb.setSelectedItem(tb1type);
    }//GEN-LAST:event_tablesMouseClicked

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
       DefaultTableModel tb1Model = (DefaultTableModel)tables.getModel();
        tb1Model.setRowCount(0);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/hotel";
            Connection connection = DriverManager.getConnection(url, "root","");

            String sql = "SELECT * FROM managing";
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);

            while (rs.next()) {

                    String Room = rs.getString("Room");
                    String Status = rs.getString("Status");
                    String Season = rs.getString("Season");
                    String Price = rs.getString("Price");
                     String Type = rs.getString("Type");

               String tbData[] = {Room,Status,Season,Price,Type}; 


               tb1Model.addRow(tbData);
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.print(e);}
    }//GEN-LAST:event_viewActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/hotel";
            Connection connection = DriverManager.getConnection(url, "root","");

            String roomNo = room.getText();
            DefaultTableModel tb1Model = (DefaultTableModel)tables.getModel();
            if(tables.getSelectedRowCount()==1)
            {
              //if single row is selected than delete
            String sql = "DELETE FROM managing WHERE Room = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString( 1, roomNo);
            statement.executeUpdate();
            }

         }catch (ClassNotFoundException | SQLException e) {
            System.out.print(e);}
    }//GEN-LAST:event_delActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/hotel";
            Connection connection = DriverManager.getConnection(url, "root","");

        //get table model
        DefaultTableModel tb1Model = (DefaultTableModel)tables.getModel();

        if(tables.getSelectedRowCount() == 1)
          {
          //if single row is selected than update
            String Room = room.getText();
            String Status = (String) combo.getSelectedItem();
            String Season = (String) combox.getSelectedItem();
            String Price = price.getText();
            //set updated value

            String sql = "UPDATE managing SET `Room` = ?, `Status` = ?, `Season` = ? , `Price` = ? WHERE `Room` = ? ";
            PreparedStatement statement = connection.prepareStatement(sql);

            statement.setString(1, Room);
            statement.setString(2, Status);
             statement.setString(3, Season);
            statement.setString( 4, Price);
             statement.setString(5, Room);
            

            statement.executeUpdate();

          }

        }catch (ClassNotFoundException | SQLException e) {
            System.out.print(e);}
    }//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      Management ab = new Management();
      ab.show();
      this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void combActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combActionPerformed

    private void roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updeladd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updeladd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updeladd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updeladd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updeladd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> comb;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JButton del;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price;
    private javax.swing.JTextField room;
    private javax.swing.JTable tables;
    private javax.swing.JLabel type;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
